### ISSUE TITLE
Unhandled exception in svcrack

### ISSUE THREAD

**Issue by sandrogauci** [EnableSecurity/sipvicious#44]
This issue was reported through the `-R` option

Command ran to reproduce issue: `['svcrack.py', '-u', '101', '-r1-999', '-t1', '-vv', 'REMOVED', '-R']`

```
Trace:
Traceback (most recent call last):
  File "svcrack.py", line 534, in main
    sipvicious.start()
  File "svcrack.py", line 283, in start
    self.getResponse()
  File "svcrack.py", line 186, in getResponse
    nonce = getNonce(authheader)
  File "/root/sipvicious/sipvicious/libs/svhelper.py", line 190, in getNonce
    _tmp = re.findall(nonceRE, pkt)
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

**Comment by sandrogauci** [comment]
Couldn't reproduce somehow. Will re-open if it surfaces again.
